title:               My digital garden
exclude:             ['_includes/notes_graph.json']
# BaseURL affects metadata in head.html
baseurl:             'https://megumi.website'

# https://jekyllrb.com/docs/configuration/options/
timezone: America/Los_Angeles

# Comment out .htaccess if you're uploading to a non-Apache server such as Netlify
include:             ['.htaccess']

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension:  true

# 'True' displays notes graph at bottom of each note
show_notes_graph: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

permalink:           slug

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
